---
title: JS Output w/ jquery
toc: true
description: A Tech Talk on outputs using HTML and Javascript. This uses jquery for easy onscreen interaction and filtering.
courses: { csa: {week: 2} }
categories: [C3.0, C3.1, C4.1]
type: hacks
---

### Markdown Table
Google [markdown cheat sheet](https://www.markdownguide.org/extended-syntax/#tables) and it lead you to an outline for how to make a table.

| Make | Model | Year | Color | Price |
|------|-------|------|-------|-------|
|Ford|Mustang|2022|Red|$35,000|
|Toyota|Camry|2022|Silver|$25,00|
|Tesla|Model S|2022|White|$80,000|
|Cadillac|Broughan|1969|Black|$10,000|
|Ford|F-350|1997|Green|$15,000|
|Ford|Excursion|2003|Green|$25,000|
|Ford|Ranger|2012|Red|$8,000|
|Kuboto|L3301 Tractor|2015|Orange|$12,000|
|Ford|Fusion Energi|2015|Green|$15,000|
|Acura|XL|2006|Grey|$10,000|
|Ford|F150 Lightning|2023|Grey|$70,000|

### HTML Table
Google [w3schools html table](https://www.w3schools.com/html/html_tables.asp) and it will lead you to a tutorial on how to make tables.

In [2]:
%%html

<h2>HTML Cell Output from Jupyter</h2>

<!-- Body contains the contents of the Document -->
<body>
    <table class="table">
        <thead>
            <tr>
                <th>Make</th>
                <th>Model</th>
                <th>Year</th>
                <th>Color</th>
                <th>Price</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Ford</td>
                <td>Mustang</td>
                <td>2022</td>
                <td>Red</td>
                <td>$35,000</td>
            </tr>
            <tr>
                <td>Toyota</td>
                <td>Camry</td>
                <td>2022</td>
                <td>Silver</td>
                <td>$25,000</td>
            </tr>
            <tr>
                <td>Tesla</td>
                <td>Model S</td>
                <td>2022</td>
                <td>White</td>
                <td>$80,000</td>
            </tr>
            <tr>
                <td>Cadillac</td>
                <td>Broughan</td>
                <td>1969</td>
                <td>Black</td>
                <td>$10,000</td>
            </tr>
            <tr>
                <td>Ford</td>
                <td>F-350</td>
                <td>1997</td>
                <td>Green</td>
                <td>$15,000</td>
            </tr>
            <tr>
                <td>Ford</td>
                <td>Excursion</td>
                <td>2003</td>
                <td>Green</td>
                <td>$25,000</td>
            </tr>
            <tr>
                <td>Ford</td>
                <td>Ranger</td>
                <td>2012</td>
                <td>Red</td>
                <td>$8,000</td>
            </tr>
            <tr>
                <td>Kuboto</td>
                <td>L3301 Tractor</td>
                <td>2015</td>
                <td>Orange</td>
                <td>$12,000</td>
            </tr>
            <tr>
                <td>Ford</td>
                <td>Fusion Energi</td>
                <td>2015</td>
                <td>Guard</td>
                <td>$25,000</td>
            </tr>
            <tr>
                <td>Acura</td>
                <td>XL</td>
                <td>2006</td>
                <td>Grey</td>
                <td>$10,000</td>
            </tr>
            <tr>
                <td>Ford</td>
                <td>F150 Lightning</td>
                <td>2024</td>
                <td>Guard</td>
                <td>$70,000</td>
            </tr>
        </tbody>
    </table>
</body>

## HTML Table in Markdown Cell with JavaScript jquery
JavaScript is a programming language that works with HTML data, CSS helps to style that data.  In this example, we are using JavaScript and CSS that was developed by others (3rd party).  Addithing the 3rd party code makes the table interactive.
- Look at the href and src on lines inside of the lines in `<head>` tags.  This is adding code to our page from others.
- Observe the `<script>` tags at the bottom of the page.  This is generating the interactive table, from the third party code, using the data `<table id="demo">` from the `<body>`.

<!-- Head contains information to Support the Document -->
<head>
    <!-- load jQuery and DataTables output style and scripts -->
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.13.4/css/jquery.dataTables.min.css">
    <script type="text/javascript" language="javascript" src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>var define = null;</script>
    <script type="text/javascript" language="javascript" src="https://cdn.datatables.net/1.13.4/js/jquery.dataTables.min.js"></script>
</head>

<!-- Body contains the contents of the Document -->
<body>
    <table id="md_demo" class="table">
        <thead>
            <tr>
                <th>Make</th>
                <th>Model</th>
                <th>Year</th>
                <th>Color</th>
                <th>Price</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Ford</td>
                <td>Mustang</td>
                <td>2022</td>
                <td>Red</td>
                <td>$35,000</td>
            </tr>
            <tr>
                <td>Toyota</td>
                <td>Camry</td>
                <td>2022</td>
                <td>Silver</td>
                <td>$25,000</td>
            </tr>
            <tr>
                <td>Tesla</td>
                <td>Model S</td>
                <td>2022</td>
                <td>White</td>
                <td>$80,000</td>
            </tr>
            <tr>
                <td>Cadillac</td>
                <td>Broughan</td>
                <td>1969</td>
                <td>Black</td>
                <td>$10,000</td>
            </tr>
            <tr>
                <td>Ford</td>
                <td>F-350</td>
                <td>1997</td>
                <td>Green</td>
                <td>$15,000</td>
            </tr>
            <tr>
                <td>Ford</td>
                <td>Excursion</td>
                <td>2003</td>
                <td>Green</td>
                <td>$25,000</td>
            </tr>
            <tr>
                <td>Ford</td>
                <td>Ranger</td>
                <td>2012</td>
                <td>Red</td>
                <td>$8,000</td>
            </tr>
            <tr>
                <td>Kuboto</td>
                <td>L3301 Tractor</td>
                <td>2015</td>
                <td>Orange</td>
                <td>$12,000</td>
            </tr>
            <tr>
                <td>Ford</td>
                <td>Fusion Energi</td>
                <td>2015</td>
                <td>Guard</td>
                <td>$25,000</td>
            </tr>
            <tr>
                <td>Acura</td>
                <td>XL</td>
                <td>2006</td>
                <td>Grey</td>
                <td>$10,000</td>
            </tr>
            <tr>
                <td>Ford</td>
                <td>F150 Lightning</td>
                <td>2024</td>
                <td>Guard</td>
                <td>$70,000</td>
            </tr>
        </tbody>
    </table>
</body>

<!-- Script is used to embed executable code -->
<script>
    $("#md_demo").DataTable();
</script>

## Hacks
This lesson teaches you about tables.  In this hack, it is important that you analyze the difference in the styles of output shown.  

- Describe a benefit of a markdown table.
    - Readability: they are easy to write and understand. They use a straightforward syntax with pipes (|) and hyphens (-) to define rows, columns, and headers, making it simple for content creators.
    - Simplicity: Markdown tables are concise and uncluttered, which makes them suitable for quickly formatting data without the verbosity of HTML or spreadsheet applications. Users can quickly create tables without having to deal with extensive HTML tags or complex spreadsheet software.
    - Compatibility: Markdown is widely supported in various text editors, online platforms, and content management systems. 

- Describe the difference between HTML and JavaScript.
    - HTML is a markup language used for creating the structure and content of web pages. It consists of a set of predefined tags and elements that define the layout, headings, paragraphs, links, images, forms, and other structural components of a web page
    - JavaScript is a dynamic scripting language used to add interactivity and functionality to web pages. It allows developers to create interactive features, respond to user actions, and manipulate the content of web pages in real-time

- Describe a benefit of a table that uses JavaScript.
    - Data Visualization: JavaScript can be used to create interactive charts and graphs within tables, providing a visual representation of data alongside the tabular format. This helps users better understand complex data sets and trends.
    - Customization: JavaScript allows developers to customize the appearance and behavior of tables to match specific design requirements and user needs. This level of control can lead to a more user-friendly and tailored user experience.
    - Data Manipulation: JavaScript can facilitate data manipulation within tables, such as calculations, updates, and data validation. This is especially useful in applications where users need to input, modify, or work with data directly in the table.


- Make your own tables, with data according to your interests.
- Try to Style the HTML table using w3schools.

In [3]:
%%html

<h2>Vivian's HTML Table on TV Shows</h2>

<body>
    <table class="table">
        <thead>
            <tr>
                <th>Name</th>
                <th>Year</th>
                <th>Rating</th>
                <th>My Rating</th>
                <th># of episodes</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Hidden Love</td>
                <td>2023</td>
                <td>4.9/5</td>
                <td>4.5/5</td>
                <td>24</td>
            </tr>
            <tr>
                <td>When I Fly Towards You</td>
                <td>2023</td>
                <td>3.9/5</td>
                <td>3.5/5</td>
                <td>24</td>
            </tr>
            <tr>
                <td>See You in my 19th Life</td>
                <td>2023</td>
                <td>4.2/5</td>
                <td>5/5</td>
                <td>12</td>
            </tr>
            <tr>
                <td>Squid Games</td>
                <td>2021</td>
                <td>4.6/5</td>
                <td>4.5/5</td>
                <td>9</td>
            </tr>
            <tr>
                <td>My Lovely Liar</td>
                <td>2023</td>
                <td>4.7/5</td>
                <td>4/5</td>
                <td>16</td>
            </tr>
            <tr>
                <td>Avatar the Last Airbender</td>
                <td>2005</td>
                <td>4.9/5</td>
                <td>4.5/5</td>
                <td>54</td>
            </tr>
            <tr>
                <td>HunterxHunter</td>
                <td>2011</td>
                <td>4.9/5</td>
                <td>5/5</td>
                <td>148</td>
            </tr>
            <tr>
                <td>Ajin Demi Human</td>
                <td>2016</td>
                <td>4.5/5</td>
                <td>4.5/5</td>
                <td>26</td>
            </tr>
            <tr>
                <td>Haikyu!!</td>
                <td>2014</td>
                <td>4.9/5</td>
                <td>4/5</td>
                <td>85</td>
            </tr>
            <tr>
                <td>Naruto</td>
                <td>2007</td>
                <td>4.3/5</td>
                <td>3.8/5</td>
                <td>720</td>
            </tr>
            <tr>
                <td>Friends</td>
                <td>1994</td>
                <td>4.9/5</td>
                <td>3.5/5</td>
                <td>236</td>
            </tr>
        </tbody>
    </table>
</body>